export const ERROR_CODES = {
  NAVER_INVALID_URL: "NAVER_INVALID_URL",
  NAVER_PRODUCT_NOT_FOUND: "NAVER_PRODUCT_NOT_FOUND",
  NAVER_QUEUE_TIMEOUT: "NAVER_QUEUE_TIMEOUT",
  NAVER_SIDECAR_UNAVAILABLE: "NAVER_SIDECAR_UNAVAILABLE",
  NAVER_PROXY_AUTH_FAILED: "NAVER_PROXY_AUTH_FAILED",
  NAVER_PROXY_UNAVAILABLE: "NAVER_PROXY_UNAVAILABLE",
  NAVER_UPSTREAM_CHALLENGE: "NAVER_UPSTREAM_CHALLENGE",
  NAVER_CAPTURE_TIMEOUT: "NAVER_CAPTURE_TIMEOUT",
  NAVER_INVALID_UPSTREAM_JSON: "NAVER_INVALID_UPSTREAM_JSON",
  NAVER_INTERNAL_ERROR: "NAVER_INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorShape {
  code: ErrorCode;
  message: string;
}
